---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: cicd
spec:
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: jenkins
    version: 5.0.24
